export const projects = [
  {
    img: "https://raw.githubusercontent.com/rajashree27/Freshly-Clone/master/screenshots/LandingPage.png",
    title: "Clone of Freshly.com",
    des: "Freshly is a New York-based prepared meal delivery company that delivers throughout the United States. As part of our unit 5 at Masai School, we were given to clone the freshly.com website.",
    demo: "",
    live: "https://freshly-clone-flame.vercel.app/",
    gitHub: "https://github.com/shravanpm/freshly.com-clone",
    technologies: ["React", "Redux", "Chakra UI"],
  },
  {
    img: "https://raw.githubusercontent.com/shravanpm/StrawberrynetClone/main/views/image/Screenshot_20230821_192810.png",
    title: "Clone of Strawberrynet.com",
    des: "Strawberrynet is a one-stop beauty destination with a diverse selection of premium brands in fragrance, make-up, skin care, hair care & derma cosmetics.",
    demo: "",
    live: "https://strawberrynet.netlify.app/",
    gitHub: "https://github.com/shravanpm/StrawberrynetClone",
    technologies: ["HTML", "CSS", "JavaScript", "MongoDB"],
  },
  {
    img: "https://raw.githubusercontent.com/shravanpm/Nykaa.com/main/src/Images/nykaa.png",
    title: "Clone of Nykaa.com",
    des: " Nykaa is an operator of an e-commerce portal designed to sell cosmetics and beauty products online.",
    demo: "",
    live: "https://nykaareact.netlify.app/",
    gitHub: "https://github.com/shravanpm/Nykaa.com",
    technologies: ["React", "Redux", "CSS", "MongoDB"],
  },
  {
    img: "https://wearethecity.in/wp-content/uploads/2014/03/Fab-Bag-Logo.png",
    title: "Clone of Fabbag",
    des: "FABBAG is an ecommerce site for purchasing beauty and makeup products. In this website user can see all the products and whichever products he wants he can add it to the cart and then proceed to the checkout page and can place the order by entering card details in the payment page.",
    demo: "",
    live: "https://vigorous-fermi-d1cb96.netlify.app/",

    gitHub: "https://github.com/abhi72181/fabbag-clone",
    technologies: ["HTML", "CSS", "JavaScript"],
  },
  // {
  // 	img: 'https://miro.medium.com/max/1400/1*S1oiZ43u5VIkZ_GiF_YeNg.png',
  // 	title: 'Clone of Ganna ',
  // 	des: 'Gaana is the one-stop solution for all your music needs. Its offers you free, unlimited access to over 30 million Hindi Songs, Bollywood Music.',

  // 	demo: '',
  // 	live: 'https://gaana-app.vercel.app/',
  // 	gitHub: 'https://github.com/gautamverma095/gaanaApp',
  // 	technologies: ['React', 'Redux', 'javaScript' , 'Express' , 'Node js.'],
  // },
  // {
  // 		img: 'https://github.com/bablikumari2/chat-clone/blob/main/client/public/Image/chatting%20room.png?raw=true',
  // 		title: 'Clone of Chit_chat App',
  // 		des: 'This is a clone of the Real time chatting app.',
  // 		demo: '',
  // 		live: 'https://client-omega-murex.vercel.app/',
  // 		gitHub: 'https://github.com/bablikumari2/chat-clone',
  // 		technologies: ['React', 'Redux', 'javaScript' , 'Express' , 'Node js.', 'Socket-io'],
  // 	},
  // 	{
  // 			img: 'https://github.com/mandarsatam/Mailchimp-Clone/blob/master/Snips/Screenshot%20(79).png?raw=true',
  // 			title: 'Mailchimp Clone',
  // 			des: 'This is a static clone of a website called Mailchimp. This clone includes landing, pricing, our story, and the resources page.',
  // 			demo: '',
  // 			live: 'https://mandarsatam.github.io/Mailchimp-Clone/',
  // 	gitHub: 'https://github.com/mandarsatam/Mailchimp-Clone',
  // 	technologies: ['HTML', 'CSS', 'javaScript'],
  // },
  // {
  // 	img: 'https://user-images.githubusercontent.com/86410106/143928012-c66d0c3c-1f94-4894-b1f0-2326be4f3087.png',
  // 	title: 'Clone of Target.com ',
  // 	des: 'This is a clone of a US-based e-commerce website for all products built with HTML, CSS, JS. Have features that allow users to sort the product on the basis of price, on the payment page users can apply promo codes',
  // 	demo: '',
  // 	live: 'https://pandeypushpendra3.github.io/target/', // deployed link
  // 	gitHub: 'https://github.com/pandeypushpendra3/target/tree/main',
  // 	technologies: [ 'HTML', 'CSS', 'javaScript'],
  // },
];
